language: node_js

node_js:
  - 10.0.0
dist: trusty
before_script:
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'